version: "2.29.1"

services:
  server:
    build: ./
    container_name: 'cloud-storage-server'
    image: 'cloud-storage:0.0.1'
    ports:
      - '8084:8084'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
  db:
    container_name: 'cloud-storage-db'
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
